### ISSUE TITLE
Count always 0 in all tables

### ISSUE THREAD

**Issue by CrazyBoy49z** [rinvex/laravel-statistics#38]
![image](https://user-images.githubusercontent.com/3448603/136957943-790e942d-ec0f-4d4d-be6e-6a9673f62655.png)

How to fix it?

**Comment by bztrn** [comment]
I faced with same issue and fixed it. I guess you didn't take any actions about Geoip settings and because of that the file of the package which named Crunch Statistics.php doesn't work properly. Please check torann/geoip package documentation and take actions written on its documentation. Or you should edit some files and remove things related with Geoip.

**Comment by Omranic** [comment]
Please check the `CrunchStatistics` job log and see if it's working correctly or having any issues. Feel free to re-open in case you still need further assistance.
